name: Set up Rust and associated tools

inputs:
  components:
    description: Comma-separated list of the additional components to install, e.g. 'clippy, rustfmt'
    default:
    required: false
  default:
    description: Set installed toolchain as a default toolchain
    default: "true"
    required: false
  profile:
    description: Rust toolchain profile
    default: minimal
    required: false

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v2
      with:
        toolchain: nightly
        components: ${{ inputs.components }}
        default: ${{ inputs.default }}
        profile: ${{ inputs.profile }}
