name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  checks: write

jobs:
  tests:
    runs-on: [self-hosted, Linux, small]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Run tests
        uses: ./.github/actions/run-mc-tests
